module.exports = {

  RESSOURCE_SUCCUSSFULLY_CREATED: "SUCCUSSFULLY_CREATED",
  RESSOURCE_SUCCUSSFULLY_UPDATED: "RESSOURCE_SUCCUSSFULLY_UPDATED",
  RESSOURCE_SUCCUSSFULLY_FETCHED: "RESSOURCE_SUCCUSSFULLY_FETCHED",
  RESSOURCE_NOT_FOUND: "RESSOURCE_NOT_FOUND",
  COMMON_CONFLICT: "CONFLICT",
  COMMON_UNAUTHORIZED: "UNAUTHORIZED",

  DB_ERROR: "DB_ERROR",

  JWT_SUCCUSSFULLY_GENERATED: "JWT_SUCCUSSFULLY_GENERATED",
  JWT_VERIFIED: "JWT_VERIFIED",
  JWT_ERROR: "JWT_ERROR",

  USER_REGISTER_SUCCESS: "REGISTER_SUCCESS",
  USER_ALREADY_EXIST: "USER_ALREADY_EXIST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_EMAIL_NOT_VERIVIED: "USER_EMAIL_NOT_VERIVIED",
  USER_EMAIL_ALREADY_VERIFIED: "USER_EMAIL_ALREADY_VERIFIED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  PASSWORD_RESET_SENT: "PASSWORD_RESET_SENT",
  EMAIL_VERIFICATION_SENT: "EMAIL_VERIFICATION_SENT",
  USER_SUCCUSSFULLY_VERIFIED: "USER_SUCCUSSFULLY_VERIFIED",

  EMAIL_SERVICE_ERROR: "EMAIL_SERVICE_ERROR",
}
